package com.example.studentmanagementsystem.repository;

import com.example.studentmanagementsystem.entity.Course;
import com.example.studentmanagementsystem.entity.Department;
import com.example.studentmanagementsystem.entity.Student;
import com.example.studentmanagementsystem.entity.Teacher;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Nested;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for CourseRepository
 *
 * @DataJpaTest provides:
 * - Configures H2 in-memory database
 * - Configures Hibernate, Spring Data, and DataSource
 * - Performs @EntityScan
 * - Turns on SQL logging
 * - Rolls back transactions at the end of each test
 *
 * Testing Strategy:
 * - Test CRUD operations against real H2 database
 * - Verify JPA relationships
 * - Test custom query methods
 * - Ensure transactional behavior
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("CourseRepository Integration Tests")
class CourseRepositoryIntegrationTest {

    @Autowired
    private CourseRepository courseRepository;

    @Autowired
    private DepartmentRepository departmentRepository;

    @Autowired
    private TeacherRepository teacherRepository;

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private TestEntityManager entityManager;

    private Department testDepartment;
    private Teacher testTeacher;
    private Course testCourse;
    private Student testStudent;

    @BeforeEach
    void setUp() {
        // Create and persist test department
        testDepartment = new Department("Computer Science");
        testDepartment = entityManager.persist(testDepartment);

        // Create and persist test teacher
        testTeacher = new Teacher("Dr. Smith", "smith@university.edu", "password123");
        testTeacher.setDepartment(testDepartment);
        testTeacher = entityManager.persist(testTeacher);

        // Create test course (not persisted yet - will be persisted in each test)
        testCourse = new Course("Data Structures", "Introduction to Data Structures and Algorithms");
        testCourse.setDepartment(testDepartment);
        testCourse.setTeacher(testTeacher);

        // Create test student
        testStudent = new Student("Alice Johnson", "CS2021001", "alice@university.edu", "password123");
        testStudent.setDepartment(testDepartment);

        entityManager.flush();
        entityManager.clear();
    }

    @Nested
    @DisplayName("CREATE (Save) Operations")
    class CreateOperations {

        @Test
        @DisplayName("Should save course successfully")
        void whenSaveCourse_thenCourseIsPersisted() {
            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();

            // Assert
            assertThat(savedCourse).isNotNull();
            assertThat(savedCourse.getId()).isNotNull();
            assertThat(savedCourse.getName()).isEqualTo("Data Structures");
            assertThat(savedCourse.getDescription()).isEqualTo("Introduction to Data Structures and Algorithms");
        }

        @Test
        @DisplayName("Should auto-generate ID when saving course")
        void whenSaveCourse_thenIdIsAutoGenerated() {
            // Arrange
            assertThat(testCourse.getId()).isNull();

            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();

            // Assert
            assertThat(savedCourse.getId()).isNotNull();
            assertThat(savedCourse.getId()).isGreaterThan(0L);
        }

        @Test
        @DisplayName("Should persist course with department relationship")
        void whenSaveCourseWithDepartment_thenRelationshipIsPersisted() {
            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            entityManager.clear();

            // Assert
            Course foundCourse = courseRepository.findById(savedCourse.getId()).orElse(null);
            assertThat(foundCourse).isNotNull();
            assertThat(foundCourse.getDepartment()).isNotNull();
            assertThat(foundCourse.getDepartment().getName()).isEqualTo("Computer Science");
        }

        @Test
        @DisplayName("Should persist course with teacher relationship")
        void whenSaveCourseWithTeacher_thenRelationshipIsPersisted() {
            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            entityManager.clear();

            // Assert
            Course foundCourse = courseRepository.findById(savedCourse.getId()).orElse(null);
            assertThat(foundCourse).isNotNull();
            assertThat(foundCourse.getTeacher()).isNotNull();
            assertThat(foundCourse.getTeacher().getName()).isEqualTo("Dr. Smith");
        }
    }

    @Nested
    @DisplayName("READ (Find) Operations")
    class ReadOperations {

        @Test
        @DisplayName("Should find course by ID")
        void whenFindById_withExistingId_thenCourseIsFound() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            Optional<Course> foundCourse = courseRepository.findById(courseId);

            // Assert
            assertThat(foundCourse).isPresent();
            assertThat(foundCourse.get().getName()).isEqualTo("Data Structures");
        }

        @Test
        @DisplayName("Should return empty when course not found by ID")
        void whenFindById_withNonExistingId_thenReturnEmpty() {
            // Act
            Optional<Course> foundCourse = courseRepository.findById(999L);

            // Assert
            assertThat(foundCourse).isEmpty();
        }

        @Test
        @DisplayName("Should find all courses")
        void whenFindAll_thenReturnAllCourses() {
            // Arrange
            courseRepository.save(testCourse);
            
            Course course2 = new Course("Algorithms", "Advanced Algorithms");
            course2.setDepartment(testDepartment);
            course2.setTeacher(testTeacher);
            courseRepository.save(course2);
            
            entityManager.flush();

            // Act
            List<Course> courses = courseRepository.findAll();

            // Assert
            assertThat(courses).hasSize(2);
            assertThat(courses).extracting(Course::getName)
                    .containsExactlyInAnyOrder("Data Structures", "Algorithms");
        }

        @Test
        @DisplayName("Should return empty list when no courses exist")
        void whenFindAll_withNoCourses_thenReturnEmptyList() {
            // Act
            List<Course> courses = courseRepository.findAll();

            // Assert
            assertThat(courses).isEmpty();
        }
    }

    @Nested
    @DisplayName("UPDATE Operations")
    class UpdateOperations {

        @Test
        @DisplayName("Should update course name successfully")
        void whenUpdateCourseName_thenChangesPersisted() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            savedCourse.setName("Advanced Data Structures");
            courseRepository.save(savedCourse);
            entityManager.flush();
            entityManager.clear();

            // Assert
            Course updatedCourse = courseRepository.findById(courseId).orElse(null);
            assertThat(updatedCourse).isNotNull();
            assertThat(updatedCourse.getName()).isEqualTo("Advanced Data Structures");
        }

        @Test
        @DisplayName("Should update course description successfully")
        void whenUpdateCourseDescription_thenChangesPersisted() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            savedCourse.setDescription("Advanced topics in Data Structures");
            courseRepository.save(savedCourse);
            entityManager.flush();
            entityManager.clear();

            // Assert
            Course updatedCourse = courseRepository.findById(courseId).orElse(null);
            assertThat(updatedCourse).isNotNull();
            assertThat(updatedCourse.getDescription()).isEqualTo("Advanced topics in Data Structures");
        }

        @Test
        @DisplayName("Should update course teacher relationship")
        void whenUpdateTeacher_thenRelationshipUpdated() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            
            Teacher newTeacher = new Teacher("Dr. Johnson", "johnson@university.edu", "password456");
            newTeacher.setDepartment(testDepartment);
            newTeacher = teacherRepository.save(newTeacher);
            
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            savedCourse.setTeacher(newTeacher);
            courseRepository.save(savedCourse);
            entityManager.flush();
            entityManager.clear();

            // Assert
            Course updatedCourse = courseRepository.findById(courseId).orElse(null);
            assertThat(updatedCourse).isNotNull();
            assertThat(updatedCourse.getTeacher().getName()).isEqualTo("Dr. Johnson");
        }
    }

    @Nested
    @DisplayName("DELETE Operations")
    class DeleteOperations {

        @Test
        @DisplayName("Should delete course by ID")
        void whenDeleteById_thenCourseIsRemoved() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            courseRepository.deleteById(courseId);
            entityManager.flush();

            // Assert
            Optional<Course> deletedCourse = courseRepository.findById(courseId);
            assertThat(deletedCourse).isEmpty();
        }

        @Test
        @DisplayName("Should delete course entity")
        void whenDelete_thenCourseIsRemoved() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            courseRepository.delete(savedCourse);
            entityManager.flush();

            // Assert
            Optional<Course> deletedCourse = courseRepository.findById(courseId);
            assertThat(deletedCourse).isEmpty();
        }

        @Test
        @DisplayName("Should verify course exists before delete")
        void whenCheckExistsBeforeDelete_thenCorrectResult() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act & Assert - Before delete
            assertThat(courseRepository.existsById(courseId)).isTrue();

            // Act - Delete
            courseRepository.deleteById(courseId);
            entityManager.flush();

            // Assert - After delete
            assertThat(courseRepository.existsById(courseId)).isFalse();
        }
    }

    @Nested
    @DisplayName("Transactional Behavior")
    class TransactionalBehavior {

        @Test
        @DisplayName("Should rollback transaction on test completion")
        void whenTestCompletes_thenTransactionIsRolledBack() {
            // Arrange & Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Assert within transaction
            assertThat(courseRepository.findById(courseId)).isPresent();
            
            // Note: After test completes, @DataJpaTest will rollback the transaction
            // so the data won't persist to subsequent tests
        }

        @Test
        @DisplayName("Should start with clean database state")
        void whenTestStarts_thenDatabaseIsClean() {
            // This test verifies isolation - it should not see data from previous tests
            // Act
            List<Course> courses = courseRepository.findAll();

            // Assert
            assertThat(courses).isEmpty(); // Clean state due to rollback
        }
    }

    @Nested
    @DisplayName("Relationship and Cascade Tests")
    class RelationshipTests {

        @Test
        @DisplayName("Should maintain many-to-many relationship with students")
        void whenCourseHasStudents_thenRelationshipIsMaintained() {
            // Arrange
            Student student1 = studentRepository.save(testStudent);
            
            Student student2 = new Student("Bob Williams", "CS2021002", "bob@university.edu", "password123");
            student2.setDepartment(testDepartment);
            student2 = studentRepository.save(student2);
            
            // Add students to course via student side (owning side)
            student1.addCourse(testCourse);
            student2.addCourse(testCourse);
            
            Course savedCourse = courseRepository.save(testCourse);
            studentRepository.save(student1);
            studentRepository.save(student2);
            entityManager.flush();
            entityManager.clear();

            // Act
            Course foundCourse = courseRepository.findById(savedCourse.getId()).orElse(null);

            // Assert
            assertThat(foundCourse).isNotNull();
            assertThat(foundCourse.getStudents()).hasSize(2);
        }

        @Test
        @DisplayName("Should allow course without department")
        void whenCourseWithoutDepartment_thenSaveSuccessfully() {
            // Arrange
            testCourse.setDepartment(null);

            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();

            // Assert
            assertThat(savedCourse.getId()).isNotNull();
            assertThat(savedCourse.getDepartment()).isNull();
        }

        @Test
        @DisplayName("Should allow course without teacher")
        void whenCourseWithoutTeacher_thenSaveSuccessfully() {
            // Arrange
            testCourse.setTeacher(null);

            // Act
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();

            // Assert
            assertThat(savedCourse.getId()).isNotNull();
            assertThat(savedCourse.getTeacher()).isNull();
        }
    }

    @Nested
    @DisplayName("Query Performance Tests")
    class QueryPerformanceTests {

        @Test
        @DisplayName("Should efficiently count all courses")
        void whenCountCourses_thenReturnCorrectCount() {
            // Arrange
            courseRepository.save(testCourse);
            
            Course course2 = new Course("Database Systems", "Intro to Databases");
            course2.setDepartment(testDepartment);
            courseRepository.save(course2);
            
            Course course3 = new Course("Web Development", "Full Stack Web Dev");
            course3.setDepartment(testDepartment);
            courseRepository.save(course3);
            
            entityManager.flush();

            // Act
            long count = courseRepository.count();

            // Assert
            assertThat(count).isEqualTo(3);
        }

        @Test
        @DisplayName("Should check existence efficiently")
        void whenCheckExistsById_thenReturnCorrectResult() {
            // Arrange
            Course savedCourse = courseRepository.save(testCourse);
            entityManager.flush();
            Long courseId = savedCourse.getId();

            // Act
            boolean exists = courseRepository.existsById(courseId);
            boolean notExists = courseRepository.existsById(999L);

            // Assert
            assertThat(exists).isTrue();
            assertThat(notExists).isFalse();
        }
    }
}
