package com.example.studentmanagementsystem.repository;

import com.example.studentmanagementsystem.entity.Department;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for DepartmentRepository
 *
 * Testing Strategy:
 * - Test CRUD operations against real H2 database
 * - Verify unique constraints
 * - Test custom query methods
 * - Ensure transactional rollback
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("DepartmentRepository Integration Tests")
class DepartmentRepositoryIntegrationTest {

    @Autowired
    private DepartmentRepository departmentRepository;

    @Autowired
    private TestEntityManager entityManager;

    private Department testDepartment;

    @BeforeEach
    void setUp() {
        testDepartment = new Department();
        testDepartment.setName("Computer Science");
    }

    // ==================== CREATE Operations ====================

    @Test
    @DisplayName("Should save department successfully")
    void whenSaveDepartment_thenDepartmentIsPersisted() {
        // Act
        Department savedDepartment = departmentRepository.save(testDepartment);
        entityManager.flush();

        // Assert
        assertThat(savedDepartment).isNotNull();
        assertThat(savedDepartment.getId()).isNotNull();
        assertThat(savedDepartment.getName()).isEqualTo("Computer Science");
    }

    @Test
    @DisplayName("Should auto-generate ID when saving department")
    void whenSaveDepartment_thenIdIsAutoGenerated() {
        // Arrange
        assertThat(testDepartment.getId()).isNull();

        // Act
        Department savedDepartment = departmentRepository.save(testDepartment);

        // Assert
        assertThat(savedDepartment.getId()).isNotNull();
        assertThat(savedDepartment.getId()).isGreaterThan(0L);
    }

    // ==================== READ Operations ====================

    @Test
    @DisplayName("Should find department by ID")
    void whenFindById_withExistingId_thenDepartmentIsFound() {
        // Arrange
        Department savedDepartment = entityManager.persist(testDepartment);
        entityManager.flush();

        // Act
        Optional<Department> found = departmentRepository.findById(savedDepartment.getId());

        // Assert
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Computer Science");
    }

    @Test
    @DisplayName("Should return empty for non-existent ID")
    void whenFindById_withNonExistentId_thenReturnEmpty() {
        // Act
        Optional<Department> found = departmentRepository.findById(999L);

        // Assert
        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("Should find department by name")
    void whenFindByName_withExistingName_thenDepartmentIsFound() {
        // Arrange
        entityManager.persist(testDepartment);
        entityManager.flush();

        // Act
        Optional<Department> found = departmentRepository.findByName("Computer Science");

        // Assert
        assertThat(found).isPresent();
        assertThat(found.get().getName()).isEqualTo("Computer Science");
    }

    @Test
    @DisplayName("Should return empty for non-existent name")
    void whenFindByName_withNonExistentName_thenReturnEmpty() {
        // Act
        Optional<Department> found = departmentRepository.findByName("Nonexistent Department");

        // Assert
        assertThat(found).isEmpty();
    }

    // ==================== EXISTENCE Checks ====================

    @Test
    @DisplayName("Should return true when name exists")
    void whenExistsByName_withExistingName_thenReturnTrue() {
        // Arrange
        entityManager.persist(testDepartment);
        entityManager.flush();

        // Act
        boolean exists = departmentRepository.existsByName("Computer Science");

        // Assert
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when name does not exist")
    void whenExistsByName_withNonExistentName_thenReturnFalse() {
        // Act
        boolean exists = departmentRepository.existsByName("Nonexistent Department");

        // Assert
        assertThat(exists).isFalse();
    }

    @Test
    @DisplayName("Should be case-sensitive when checking name existence")
    void whenExistsByName_withDifferentCase_thenReturnFalse() {
        // Arrange
        entityManager.persist(testDepartment);
        entityManager.flush();

        // Act
        boolean exists = departmentRepository.existsByName("computer science");

        // Assert
        assertThat(exists).isFalse();
    }

    // ==================== UPDATE Operations ====================

    @Test
    @DisplayName("Should update department name successfully")
    void whenUpdateDepartment_thenChangesArePersisted() {
        // Arrange
        Department savedDepartment = entityManager.persist(testDepartment);
        entityManager.flush();
        entityManager.clear();

        // Act
        Department departmentToUpdate = departmentRepository.findById(savedDepartment.getId()).orElseThrow();
        departmentToUpdate.setName("Mathematics");
        departmentRepository.save(departmentToUpdate);
        entityManager.flush();
        entityManager.clear();

        // Assert
        Department updated = entityManager.find(Department.class, savedDepartment.getId());
        assertThat(updated.getName()).isEqualTo("Mathematics");
    }

    // ==================== DELETE Operations ====================

    @Test
    @DisplayName("Should delete department successfully")
    void whenDeleteDepartment_thenDepartmentIsRemoved() {
        // Arrange
        Department savedDepartment = entityManager.persist(testDepartment);
        Long deptId = savedDepartment.getId();
        entityManager.flush();

        // Act
        departmentRepository.deleteById(deptId);
        entityManager.flush();

        // Assert
        Department deleted = entityManager.find(Department.class, deptId);
        assertThat(deleted).isNull();
    }

    // ==================== Query Methods ====================

    @Test
    @DisplayName("Should find all departments")
    void whenFindAll_thenAllDepartmentsAreReturned() {
        // Arrange
        Department dept1 = new Department();
        dept1.setName("Computer Science");
        Department dept2 = new Department();
        dept2.setName("Mathematics");

        entityManager.persist(dept1);
        entityManager.persist(dept2);
        entityManager.flush();

        // Act
        var departments = departmentRepository.findAll();

        // Assert
        assertThat(departments).hasSize(2);
        assertThat(departments).extracting(Department::getName)
                .containsExactlyInAnyOrder("Computer Science", "Mathematics");
    }

    @Test
    @DisplayName("Should count departments correctly")
    void whenCount_thenReturnCorrectCount() {
        // Arrange
        Department dept1 = new Department();
        dept1.setName("Computer Science");
        Department dept2 = new Department();
        dept2.setName("Mathematics");

        entityManager.persist(dept1);
        entityManager.persist(dept2);
        entityManager.flush();

        // Act
        long count = departmentRepository.count();

        // Assert
        assertThat(count).isEqualTo(2);
    }
}
