package com.example.studentmanagementsystem.repository;

import com.example.studentmanagementsystem.entity.Department;
import com.example.studentmanagementsystem.entity.Student;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.test.context.ActiveProfiles;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for StudentRepository
 *
 * @DataJpaTest provides:
 * - Configures H2 in-memory database
 * - Configures Hibernate, Spring Data, and DataSource
 * - Performs @EntityScan
 * - Turns on SQL logging
 * - Rolls back transactions at the end of each test
 *
 * Testing Strategy:
 * - Test actual database operations
 * - Verify JPA relationships
 * - Test custom query methods
 * - Ensure transactional behavior
 */
@DataJpaTest
@ActiveProfiles("test")
@DisplayName("StudentRepository Integration Tests")
class StudentRepositoryIntegrationTest {

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private DepartmentRepository departmentRepository;

    @Autowired
    private TestEntityManager entityManager;

    private Department testDepartment;
    private Student testStudent;

    @BeforeEach
    void setUp() {
        // Arrange: Setup test data using TestEntityManager
        testDepartment = new Department();
        testDepartment.setName("Computer Science");
        testDepartment = entityManager.persist(testDepartment);

        testStudent = new Student();
        testStudent.setName("John Doe");
        testStudent.setEmail("john.doe@test.com");
        testStudent.setRoll("CS001");
        testStudent.setPassword("encodedPassword");
        testStudent.setDepartment(testDepartment);
    }

    // ==================== CREATE (Save) Operations ====================

    @Test
    @DisplayName("Should save student successfully")
    void whenSaveStudent_thenStudentIsPersisted() {
        // Act: Save student to database
        Student savedStudent = studentRepository.save(testStudent);

        // Flush to ensure database synchronization
        entityManager.flush();
        entityManager.clear();

        // Assert: Verify student was persisted correctly
        assertThat(savedStudent).isNotNull();
        assertThat(savedStudent.getId()).isNotNull();
        assertThat(savedStudent.getName()).isEqualTo("John Doe");
        assertThat(savedStudent.getEmail()).isEqualTo("john.doe@test.com");
        assertThat(savedStudent.getRoll()).isEqualTo("CS001");
        assertThat(savedStudent.getDepartment()).isNotNull();
        assertThat(savedStudent.getDepartment().getName()).isEqualTo("Computer Science");
    }

    @Test
    @DisplayName("Should auto-generate ID when saving student")
    void whenSaveStudent_thenIdIsAutoGenerated() {
        // Arrange: Ensure ID is null before save
        assertThat(testStudent.getId()).isNull();

        // Act: Save student
        Student savedStudent = studentRepository.save(testStudent);

        // Assert: Verify ID was auto-generated
        assertThat(savedStudent.getId()).isNotNull();
        assertThat(savedStudent.getId()).isGreaterThan(0L);
    }

    @Test
    @DisplayName("Should maintain relationship with department when saving")
    void whenSaveStudentWithDepartment_thenRelationshipIsMaintained() {
        // Act: Save student with department
        Student savedStudent = studentRepository.save(testStudent);
        entityManager.flush();
        entityManager.clear();

        // Assert: Verify relationship is maintained after persistence
        Student foundStudent = entityManager.find(Student.class, savedStudent.getId());
        assertThat(foundStudent.getDepartment()).isNotNull();
        assertThat(foundStudent.getDepartment().getId()).isEqualTo(testDepartment.getId());
        assertThat(foundStudent.getDepartment().getName()).isEqualTo("Computer Science");
    }

    // ==================== READ (Find) Operations ====================

    @Test
    @DisplayName("Should find student by ID when student exists")
    void whenFindById_withExistingId_thenStudentIsFound() {
        // Arrange: Save student first
        Student savedStudent = entityManager.persist(testStudent);
        entityManager.flush();

        // Act: Find by ID
        Optional<Student> found = studentRepository.findById(savedStudent.getId());

        // Assert: Verify student was found
        assertThat(found).isPresent();
        assertThat(found.get().getId()).isEqualTo(savedStudent.getId());
        assertThat(found.get().getEmail()).isEqualTo("john.doe@test.com");
    }

    @Test
    @DisplayName("Should return empty when finding by non-existent ID")
    void whenFindById_withNonExistentId_thenReturnEmpty() {
        // Act: Find by non-existent ID
        Optional<Student> found = studentRepository.findById(999L);

        // Assert: Verify no student was found
        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("Should find student by email when email exists")
    void whenFindByEmail_withExistingEmail_thenStudentIsFound() {
        // Arrange: Save student first
        entityManager.persist(testStudent);
        entityManager.flush();

        // Act: Find by email (custom query method)
        Optional<Student> found = studentRepository.findByEmail("john.doe@test.com");

        // Assert: Verify student was found
        assertThat(found).isPresent();
        assertThat(found.get().getEmail()).isEqualTo("john.doe@test.com");
        assertThat(found.get().getName()).isEqualTo("John Doe");
    }

    @Test
    @DisplayName("Should return empty when finding by non-existent email")
    void whenFindByEmail_withNonExistentEmail_thenReturnEmpty() {
        // Act: Find by non-existent email
        Optional<Student> found = studentRepository.findByEmail("nonexistent@test.com");

        // Assert: Verify no student was found
        assertThat(found).isEmpty();
    }

    @Test
    @DisplayName("Should find student by roll number when roll exists")
    void whenFindByRoll_withExistingRoll_thenStudentIsFound() {
        // Arrange: Save student first
        entityManager.persist(testStudent);
        entityManager.flush();

        // Act: Find by roll number (custom query method)
        Optional<Student> found = studentRepository.findByRoll("CS001");

        // Assert: Verify student was found
        assertThat(found).isPresent();
        assertThat(found.get().getRoll()).isEqualTo("CS001");
        assertThat(found.get().getName()).isEqualTo("John Doe");
    }

    @Test
    @DisplayName("Should return empty when finding by non-existent roll")
    void whenFindByRoll_withNonExistentRoll_thenReturnEmpty() {
        // Act: Find by non-existent roll
        Optional<Student> found = studentRepository.findByRoll("INVALID001");

        // Assert: Verify no student was found
        assertThat(found).isEmpty();
    }

    // ==================== EXISTENCE Check Operations ====================

    @Test
    @DisplayName("Should return true when checking if email exists")
    void whenExistsByEmail_withExistingEmail_thenReturnTrue() {
        // Arrange: Save student first
        entityManager.persist(testStudent);
        entityManager.flush();

        // Act: Check if email exists
        boolean exists = studentRepository.existsByEmail("john.doe@test.com");

        // Assert: Verify email exists
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when checking if non-existent email exists")
    void whenExistsByEmail_withNonExistentEmail_thenReturnFalse() {
        // Act: Check if non-existent email exists
        boolean exists = studentRepository.existsByEmail("nonexistent@test.com");

        // Assert: Verify email does not exist
        assertThat(exists).isFalse();
    }

    @Test
    @DisplayName("Should return true when checking if roll exists")
    void whenExistsByRoll_withExistingRoll_thenReturnTrue() {
        // Arrange: Save student first
        entityManager.persist(testStudent);
        entityManager.flush();

        // Act: Check if roll exists
        boolean exists = studentRepository.existsByRoll("CS001");

        // Assert: Verify roll exists
        assertThat(exists).isTrue();
    }

    @Test
    @DisplayName("Should return false when checking if non-existent roll exists")
    void whenExistsByRoll_withNonExistentRoll_thenReturnFalse() {
        // Act: Check if non-existent roll exists
        boolean exists = studentRepository.existsByRoll("INVALID001");

        // Assert: Verify roll does not exist
        assertThat(exists).isFalse();
    }

    // ==================== UPDATE Operations ====================

    @Test
    @DisplayName("Should update student details successfully")
    void whenUpdateStudent_thenChangesArePersisted() {
        // Arrange: Save student first
        Student savedStudent = entityManager.persist(testStudent);
        entityManager.flush();
        entityManager.clear();

        // Act: Update student details
        Student studentToUpdate = studentRepository.findById(savedStudent.getId()).orElseThrow();
        studentToUpdate.setName("Jane Doe Updated");
        studentToUpdate.setEmail("jane.updated@test.com");
        Student updatedStudent = studentRepository.save(studentToUpdate);
        entityManager.flush();
        entityManager.clear();

        // Assert: Verify updates were persisted
        Student verifyStudent = entityManager.find(Student.class, savedStudent.getId());
        assertThat(verifyStudent.getName()).isEqualTo("Jane Doe Updated");
        assertThat(verifyStudent.getEmail()).isEqualTo("jane.updated@test.com");
        assertThat(verifyStudent.getRoll()).isEqualTo("CS001"); // Should remain unchanged
    }

    // ==================== DELETE Operations ====================

    @Test
    @DisplayName("Should delete student successfully")
    void whenDeleteStudent_thenStudentIsRemoved() {
        // Arrange: Save student first
        Student savedStudent = entityManager.persist(testStudent);
        Long studentId = savedStudent.getId();
        entityManager.flush();

        // Act: Delete student
        studentRepository.deleteById(studentId);
        entityManager.flush();

        // Assert: Verify student was deleted
        Student deletedStudent = entityManager.find(Student.class, studentId);
        assertThat(deletedStudent).isNull();
    }

    // ==================== Transactional Behavior ====================

    @Test
    @DisplayName("Should rollback transaction on test completion")
    void whenTestCompletes_thenTransactionIsRolledBack() {
        // Arrange & Act: Save student
        Student savedStudent = studentRepository.save(testStudent);
        entityManager.flush();

        // Assert: Student exists during test
        assertThat(studentRepository.findById(savedStudent.getId())).isPresent();

        // Note: After this test completes, @DataJpaTest will rollback the transaction
        // This ensures test isolation and database state is not affected
    }

    // ==================== Edge Cases ====================

    @Test
    @DisplayName("Should handle saving student without department")
    void whenSaveStudentWithoutDepartment_thenStudentIsSaved() {
        // Arrange: Create student without department
        Student studentWithoutDept = new Student();
        studentWithoutDept.setName("No Dept Student");
        studentWithoutDept.setEmail("nodept@test.com");
        studentWithoutDept.setRoll("CS002");
        studentWithoutDept.setPassword("password");

        // Act: Save student
        Student savedStudent = studentRepository.save(studentWithoutDept);

        // Assert: Verify student was saved without department
        assertThat(savedStudent.getId()).isNotNull();
        assertThat(savedStudent.getDepartment()).isNull();
    }

    @Test
    @DisplayName("Should preserve entity manager state across operations")
    void whenPerformingMultipleOperations_thenStateIsConsistent() {
        // Arrange: Save multiple students
        Student student1 = new Student("Student 1", "CS001", "s1@test.com", "pass1");
        Student student2 = new Student("Student 2", "CS002", "s2@test.com", "pass2");

        // Act: Save both students
        studentRepository.save(student1);
        studentRepository.save(student2);
        entityManager.flush();

        // Assert: Both students should be findable
        assertThat(studentRepository.findByEmail("s1@test.com")).isPresent();
        assertThat(studentRepository.findByEmail("s2@test.com")).isPresent();
        assertThat(studentRepository.count()).isEqualTo(2);
    }
}
